// <auto-generated />
namespace MVCIdentity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class modified_photo_category : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modified_photo_category));
        
        string IMigrationMetadata.Id
        {
            get { return "201803160921191_modified_photo_category"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
